spring.application.name=springdemo

#MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/springdemo
spring.datasource.username=root
spring.datasource.password=MySQLTej@111111
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#OpenAI
openai.api.key=
openai.api.base-url=https://integrate.api.nvidia.com/v1/chat/completions
openai.model=


